<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\ShopSpree.Application\ShopSpree.Application.csproj" />
    <ProjectReference Include="..\ShopSpree.Infrastructure\ShopSpree.Infrastructure.csproj" />
    <ProjectReference Include="..\ShopSpree.Shared\ShopSpree.Shared.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

</Project>
